package kaliandapet100;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import com.flashsale.services.FlashsaleWebService;
import com.flashsale.services.LoginWebService;
import com.flashsale.services.Ticket;
import model.User;

public class FormTicketDetails extends javax.swing.JFrame {

    private User user;
    private Ticket ticket;
    public FormTicketDetails(Ticket ticket, User user) {
        this.ticket = ticket;
        this.user = user;
        initComponents();
        setLocationRelativeTo(null);
        labelUsername.setText(user.getUsername());
        JOptionPane.showConfirmDialog(this, "Username : " + user.getUsername());
        populateTicketData();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    private void populateTicketData() {
        // Format price as Indonesian currency
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        String formattedPrice = currencyFormat.format(ticket.getPrice());

        // Format dates
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd MMMM yyyy");

        // Populate ticket data
        txtID.setText(ticket.getId());
        txtTitle.setText(ticket.getTitle());
        txtCreator.setText(ticket.getCreator());
        txtDesc.setText(ticket.getDesc());
        txtPrice.setText(formattedPrice);
        txtStock.setText(String.valueOf(ticket.getStock()));

        // Set image based on ticket ID (you may need to adjust this logic)
        try {
            // Default to Bruno Mars image if it exists
            ImageIcon icon = new ImageIcon(getClass().getResource("/Images/brunoMars.jpg"));

            // You can add custom logic to choose different images based on the ticket ID
            if (ticket.getId().startsWith("A")) {
                // Use default Bruno Mars
            } else if (ticket.getId().startsWith("B")) {
                // Try to load a different image for B tickets
                ImageIcon altIcon = new ImageIcon(getClass().getResource("/Images/taeyeon.jpg"));
                if (altIcon.getIconWidth() > 0) { // Check if image was loaded
                    icon = altIcon;
                }
            } else if (ticket.getId().startsWith("C")) {
                ImageIcon altIcon = new ImageIcon(getClass().getResource("/Images/ive.jpg"));
                if (altIcon.getIconWidth() > 0) {
                    icon = altIcon;
                }
            } else if (ticket.getId().startsWith("D")) {
                ImageIcon altIcon = new ImageIcon(getClass().getResource("/Images/hivi.jpg"));
                if (altIcon.getIconWidth() > 0) {
                    icon = altIcon;
                }
            } else if (ticket.getId().startsWith("E")) {
                ImageIcon altIcon = new ImageIcon(getClass().getResource("/Images/james.jpg"));
                if (altIcon.getIconWidth() > 0) {
                    icon = altIcon;
                }
            }

            imageEvent.setIcon(icon);
        } catch (Exception e) {
            // If there's an error loading the image, just continue
            System.err.println("Error loading image: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();
        price_label = new javax.swing.JLabel();
        stock_label = new javax.swing.JLabel();
        txtID = new java.awt.TextField();
        txtTitle = new java.awt.TextField();
        txtPrice = new java.awt.TextField();
        txtStock = new java.awt.TextField();
        title_label1 = new javax.swing.JLabel();
        txtCreator = new java.awt.TextField();
        title_label2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        btnCheckOut = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        imageEvent = new javax.swing.JLabel();
        id_label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(200, 169, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("Ticket Details");
        jPanel1.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 230, -1));

        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUsername.setText("Username");
        jPanel1.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 130, -1));

        title_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title_label.setForeground(new java.awt.Color(255, 255, 255));
        title_label.setText("Title : ");
        jPanel1.add(title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        price_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        price_label.setForeground(new java.awt.Color(255, 255, 255));
        price_label.setText("Price : ");
        jPanel1.add(price_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        stock_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stock_label.setForeground(new java.awt.Color(255, 255, 255));
        stock_label.setText("Stock : ");
        jPanel1.add(stock_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        txtID.setBackground(new java.awt.Color(245, 232, 212));
        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtID.setForeground(new java.awt.Color(74, 52, 46));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 370, -1));

        txtTitle.setBackground(new java.awt.Color(245, 232, 212));
        txtTitle.setEditable(false);
        txtTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(74, 52, 46));
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 370, -1));

        txtPrice.setBackground(new java.awt.Color(245, 232, 212));
        txtPrice.setEditable(false);
        txtPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(74, 52, 46));
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 370, -1));

        txtStock.setBackground(new java.awt.Color(245, 232, 212));
        txtStock.setEditable(false);
        txtStock.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStock.setForeground(new java.awt.Color(74, 52, 46));
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 370, -1));

        title_label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title_label1.setForeground(new java.awt.Color(255, 255, 255));
        title_label1.setText("Creator : ");
        jPanel1.add(title_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        txtCreator.setBackground(new java.awt.Color(245, 232, 212));
        txtCreator.setEditable(false);
        txtCreator.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCreator.setForeground(new java.awt.Color(74, 52, 46));
        jPanel1.add(txtCreator, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 370, -1));

        title_label2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title_label2.setForeground(new java.awt.Color(255, 255, 255));
        title_label2.setText("Description :");
        jPanel1.add(title_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(245, 232, 212));

        txtDesc.setEditable(false);
        txtDesc.setBackground(new java.awt.Color(245, 232, 212));
        txtDesc.setColumns(20);
        txtDesc.setForeground(new java.awt.Color(74, 52, 46));
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 370, 60));

        btnCheckOut.setBackground(new java.awt.Color(228, 123, 46));
        btnCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCheckOut.setForeground(new java.awt.Color(255, 249, 240));
        btnCheckOut.setText("Check Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 110, 38));

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 249, 240));
        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 38, 38));

        imageEvent.setBackground(new java.awt.Color(255, 255, 255));
        imageEvent.setForeground(new java.awt.Color(74, 52, 46));
        imageEvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brunoMars.jpg"))); // NOI18N
        jPanel1.add(imageEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 148, 220));

        id_label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        id_label1.setForeground(new java.awt.Color(255, 255, 255));
        id_label1.setText("ID : ");
        jPanel1.add(id_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 467));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        FormCheckout checkoutForm = new FormCheckout(ticket, user);
        checkoutForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FormListTicket listForm = new FormListTicket(user);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTicketDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JLabel id_label1;
    private javax.swing.JLabel imageEvent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel price_label;
    private javax.swing.JLabel stock_label;
    private javax.swing.JLabel title_label;
    private javax.swing.JLabel title_label1;
    private javax.swing.JLabel title_label2;
    private java.awt.TextField txtCreator;
    private javax.swing.JTextArea txtDesc;
    private java.awt.TextField txtID;
    private java.awt.TextField txtPrice;
    private java.awt.TextField txtStock;
    private java.awt.TextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
